name: Jacko, Physicist
markdown: kramdown
permalink: pretty
collections: 
  posts:
    output: true
  patents:
    output: true
  publications:
    output: true
  abstracts:
    output: true

theme: jekyll-theme-hacker